### ISSUE TITLE
Invalid characters in NASAL

### ISSUE THREAD

**Issue by MaksimKayumov** [KavehYousefi/Esoteric-programming-languages#3]
I'm sorry, but your NASAL interpreter is wrong. Any other characters are invalid even when they are used as arguments of "m" or "ɳ" commands. I already fixed programs on esolangs.org page

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your notification and apologize sincerely for my misunderstanding.

I imputed the equivalency to BitBrain to condition a tacit propagation of its concepts into NASAL's type system, that is, the introduction of numeric entities into its syntax. I have in the interim, hopefully, rectified the misfeatures.

I thank you for your efforts.

Yours faithfully,

Kaveh Yousefi
