### ISSUE TITLE
Output in Quests

### ISSUE THREAD

**Issue by MaksimKayumov** [KavehYousefi/Esoteric-programming-languages#5]
Quests has No I/O

**Comment by MaksimKayumov** [comment]
I have added a new command so there would be I/O

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your notification and will incorporate the modifications in my implementation.

Yours faithfully,

Kaveh Yousefi

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I have adjusted my implementation to the most recent Quests language standard.

I again thank you for your commitment.

Yours faithfully,

Kaveh Yousefi
