### ISSUE TITLE
"d" in NABC

### ISSUE THREAD

**Issue by MaksimKayumov** [KavehYousefi/Esoteric-programming-languages#8]
It was intended that d is always used to seperate commands, even if they are seperated by a newline they  still need a d

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your message and apologize for the misconstruction.

I will erelong adjust my interpreter implementation.

Yours faithfully,

Kaveh Yousefi

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I have concluded the interpreter's rectification anent the requisite “d” separators across adjacent lines.

I thank you for your efforts.

Yours faithfully,

Kaveh Yousefi
