### ISSUE TITLE
PushDupAddSub

### ISSUE THREAD

**Issue by MaksimKayumov** [KavehYousefi/Esoteric-programming-languages#9]
If I read it correctly when it divides it pushes remainder first, and then quotient after it. So if stack is (bottom on the left and top on the right) [7 2] stack will be [1 3] after command / is performed, with remainder at the bottom. If it is, then it's not correct and it needs to push quotient first, followed by remainder, in fact this is what makes the language Turing-complete. Sorry if I read it wrong.

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your notification.

I reminisce a rather sumptuous expenditure of time in the operator description's diction without a conclusive resolution of its veridical construe, having adjudged the ultimate solution in a slightly aleatory mode. Proceeding for your very sensible argumentation, I will adjust my implementation, as well as the appertaining examples on the respective Esolang page, accordingly.

Yours faithfully,

Kaveh Yousefi
